# Generated by Django 3.1.1 on 2020-10-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201017_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='uncategorized', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.category'),
        ),
    ]
