# Generated by Django 3.1.1 on 2020-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201017_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='comment_image',
            field=models.CharField(default=0, max_length=2089),
            preserve_default=False,
        ),
    ]
