# Generated by Django 3.1.1 on 2020-10-18 08:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_author_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
