# Generated by Django 3.1.1 on 2020-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20201022_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Post meta keywords'),
        ),
    ]
